name: CI Pipeline

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: pip install pytest
      
    - name: Install dependencies
      run: pip install flask

    - name: Run tests
      run: pytest test.py

    - name: Run flask
      run: python flask.py

    - name: Run flask
      run: python flask.py
